var l,q=[atob("MTI3LjAuMC4xOjEwMDE="),atob("MC4xLjAuMToxMDAx")],aa=atob("cGx1Z2luLnYzLmludGVybmV0ZG93bmxvYWRtYW5hZ2VyLmNvbQ=="),s=atob("amVhb2hobGFqZWpvZGZqYWRjcG9ucG5qZ2tpaWtvY24="),ba=atob("Q2hyb21lX1JlbmRlcldpZGdldEhvc3RIV05E"),ca=["object","xmlhttprequest","other"],da=[301,302,303,307],t=["http://*/*","https://*/*"],ea=/:\/\/.+\/([^/]+?(?:\.([^./]+?))?)(?=[?#]|$)/,fa=/\.([^.\\/]*?)(?=(?:\.[0-9]+)*)$/,ga=new RegExp(atob("Xig/Omh0dHA6Ly93d3d8aHR0cHM6Ly9zZWN1cmUpXC5pbnRlcm5ldGRvd25sb2FkbWFuYWdlclwuY29tLyg/OmF1dG9yZWd8ZmlsbHJlZ2Zvcm0pXC5odG1sXD9kPQ=="),
"i"),w=new RegExp(atob("Xig/Omh0dHB8aHR0cHMpOi8vd3d3XC55b3V0dWJlXC5jb20vd2F0Y2hcPw=="),"i"),ha=atob("dmlkZW9wbGF5YmFjaw=="),ia={16:1,17:2,18:4,45:8,46:16},ja={http:1,https:129,ftp:2,ftps:130,rtmp:3,rtmpt:3,rtmpe:3,mms:4,idmreg:159},ka={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT","text/xml":"XML|F4M","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS",
"application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/pdf":"PDF","application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI",
"application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/flv":"FLV","video/mp2t":"TS","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG","video/mpg4":"MP4|M4V","video/msvideo":"AVI",
"video/quicktime":"MOV","video/webm":"WEBM","video/x-mp4":"MP4|M4V","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","video/x-flash-video":"FLV","video/x-flv":"FLV","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA",
"image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};function x(){this.b=this.constructor.prototype.d++}x.prototype.d=1;function y(a,b,c,d){this.id=a;this.port=b;this.b=c;this.url=d}y.prototype.a=0;function la(a,b,c){this.id=[a,b].toString();this.a=0>c?null:[a,c].toString()}
function z(a,b,c,d,e,g){if(a){c=["MSG#",a,"#",b,"#",c,"#",d];this.e=a;this.d=b;this.f=d;this.a=e||[];this.h=c;if(e)for(a=0;a<e.length;a++)c.push(":",e[a]||0);if(g)for(var f in g)if(e=g[f],null!=e)if(c.push(",",f,"="),"number"==typeof e)c.push(e);else{b=a=e.length;for(d=0;d<b;){var h=e.charCodeAt(d++);128<=h&&(2048<=h?(a+=2,h-55296&56320||d++):a++)}c.push(a,":",e)}}else this.c=new FileReader}function ma(a){a.K||(a.h.push(";"),a.K=!0);return new Blob(a.h)}
function A(a,b,c){a.K?a.m(a):(b.a=c||0,b.b=0,a.c.onload=a.Ia.bind(a,b),B(a,b,0,50))}l=z.prototype;
l.Ia=function(a){for(var b=this.c.result;;)switch(a.b){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.m(this);a.b=1}var g=e.length+1,d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.m(this);this.e=parseInt(d[1]);this.d=parseInt(d[2]);this.f=parseInt(d[4]);b=b.slice(g);a.a+=g;a.b++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return B(this,a,b.length,100);a.b=4}g=e.length+1;this.a=d=e.split(":");
for(e=0;e<d.length;e++)c=d[e],d[e]=c.includes(".")?parseFloat(c):parseInt(c);b=b.slice(g);a.a+=g;a.b++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));var d=c.shift().split(":",2),f=d.shift(),g=f.length,e=!1;if(d.length)g++;else{if(!c.length)return B(this,a,b.length,25);e=!0}d=f.split("=",3);if(2!=d.length)return this.m(this);c=parseInt(d[0]);d=parseInt(d[1]);a.a+=g;a.b++;if(e){this[c]=d;b=b.slice(g);a.b++;break}a.d=c;a.c=d;b=a.c;g=a.a;a=a.slice(g,g+b);a.size==b?this.c.readAsText(a):
this.m(this);return;case 3:return this[a.d]=b,a.a+=a.c,a.b++,B(this,a,0,21);case 4:switch(b[0]){case ",":a.b=2;b=b.slice(1);break;case ";":a.b++;break;default:return this.m(this)}a.a++;break;case 5:this.K=!0;this.C(this);a.size>a.a&&(b=new z,b.C=this.C,b.m=this.m,A(b,a,a.a));return}};function B(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.c.readAsBinaryString(b.slice(e,c+d)):a.m(a)}l.g=null;l.C=null;l.m=null;l.K=!1;
function C(){var a=this.constructor.prototype,b;for(b in a)this[b]=a[b].bind(this);b=navigator.userAgent;a=b.match(/(\b(?!(?:Safari|Chrome)\/)\w+\/[\d\.]+\b)[^()]*$/);if(b=b.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/))this.ca=b[1]<<24|b[2]<<22|b[3]<<8|b[4],this.Aa=b[0],this.xa=a?a[1]:b[0],this.ua=[],this.O=!1,this.c={},this.j={},this.a={},this.o={},this.b={},this.h={},this.e={},this.d={},this.v={},this.W="",this.X=!0,this.ba=this.Ba=1,this.f=null,this.T=1,this.w=!1,this.I=this.P=0,this.ta=null,
this.V=this.sa=!1,this.za=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_link"),contexts:["link"],onclick:this.Ca,enabled:!1}),this.ya=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_all"),contexts:["page"],onclick:this.ea,enabled:!1}),this.va=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_selected"),contexts:["selection"],onclick:this.ea,enabled:!1}),this.u=[this.za,this.ya,this.va],chrome.windows.onCreated.addListener(this.ma),
chrome.windows.onRemoved.addListener(this.na),chrome.windows.onFocusChanged.addListener(this.Ta),chrome.tabs.onActivated.addListener(this.Oa),chrome.tabs.onUpdated.addListener(this.Qa),chrome.tabs.onAttached.addListener(this.Pa),this.M(),chrome.windows.getAll(null,this.Fa)}function D(a,b,c,d,e){a=a.e;return b in a?a[b]:a[b]=new y(b,c,d,e)}function E(a,b){var c=a.h[b];c&&delete a.h[b];return c}l=C.prototype;
l.M=function(){var a=new WebSocket("ws://"+q[this.P%q.length]+"/?cid="+Math.random().toString().substr(2,9),aa);this.da=a;a.onopen=this.ia;a.onclose=this.R;a.onmessage=this.Na;1==a.readyState?this.ia():3==a.readyState&&this.R()};l.ia=function(){this.w=!0;this.ba=1;var a={};a[112]=this.xa;a[113]=this.Aa;a[114]=ba;F(this,2,0,[3,1,7,0],a)};
l.R=function(){this.da=null;if(this.w){this.w=!1;this.v={};for(var a;a=this.ua.shift();){var b=a.shift();b.removeListener.apply(b,a)}for(a=0;a<this.u.length;a++)chrome.contextMenus.update(this.u[a],{enabled:!1});this.O=!1}a=++this.P;b=q.length;10>a/b&&(a==b&&this.X&&this.L(),!a||a%b?this.M():window.setTimeout(this.M,15E3))};l.Na=function(a){var b=new z;b.C=this.Ka;b.m=this.R;A(b,a.data)};
function F(a,b,c,d,e){if(!a.w)return!1;var g=a.ba++;b=new z(g,b,1,c,d,e);a.da.send(ma(b));c&1&&(a.v[g]=b);return!0}
function G(a,b){var c=a.d;if(b.a){var d=b.a[6],e=d&&c[d];if(e){var g=e.type;return!g||"image"==g||e.D?(b.g=e.port.id,b.j=d,!0):!1}}var f=a.a,h=a.e,k=b[6],m=b[17],n=b[50],r=b[7],u,v;for(d in c){var e=c[d],p=e.url;if(p){if(p==k||p==m)if(g=e.type,!g||"image"==g||e.D)return b.g=e.port.id,b.j=parseInt(d),!0;p==n&&(v=e.port.id)}}for(d in h)if(c=h[d],p=c.url){if(p==k||p==m||p==n)if(e=c.port,r&&(g=f[e.tabId])&&g.url!=r&&(e=null),e)return b.g=e.id,!0;p==r&&(u=c.port.id)}return v||u?(b.g=v||u,!0):!1}
l.fa=function(a,b,c,d){if(b)return d?(b=(c=d.shift())&&this.a[c.id])?a.g=b.id:null:null;if(a.g)return a.g;if(a.a){var e=a.a[7];if(e&&this.j[e])return a.g=e}if(G(this,a))return a.g;d=this.j;var g=a[50],f=a[7];for(e in d){b=d[e];if(b.url==g){a.g=e;break}a.g||b.url!=f||(a.g=e)}if(a.g)return a.g;f&&chrome.tabs.query({url:f},H(this,a,!0,c))};
l.N=function(a,b,c,d,e){var g=a.tabId,f=a.frameId,h=a.windowId,k;if(void 0===b&&(b=new I(this,a,!0),null==h&&(a.a?(chrome.tabs.get(g,J(b,2)),chrome.windows.getLastFocused(J(b,3))):(h=this.a[g],a.windowId=h&&h.windowId)),null==f&&a.url&&chrome.webNavigation.getAllFrames({tabId:g},J(b,4)),b.c()))return;c&&0<=c.index?a.windowId=c.windowId:d&&(a.windowId=d.id);if(e)for(c=e.length-1;0<=c;c--)if(d=e[c],!d.Va&&d.frameId&&d.url==a.url){f=a.frameId=d.frameId;k=d.parentFrameId;break}null==f?a.url||a.postMessage([11,
g,null,!0,a.k]):(c=[g,f].toString(),e=this.o[c],this.a[c]=a,0<=k&&(a.b=[g,k].toString()),e&&(a.requestId=e.b,a.k=e.k,(k=e.p)&&a.url!=k&&(a.p=k),!a.b&&e.a&&(a.b=e.a)),a.postMessage([11,g,f,!a.url,a.k]))};l.Y=function(a,b,c,d){var e=K(a,!0);if(!e)return 0;if(1==e&&void 0===d)return chrome.cookies.getAll({url:a},H(this,a,b,c)),-1;"object"==typeof d&&(d=L(d));var e=[e],g={};g[6]=a;g[8]=c;g[51]=d;g[54]=navigator.userAgent;g[7]=b;F(this,14,0,e,g);return 3};
l.ra=function(a,b,c,d,e){if(!d){if(!a||!a.length)return;c||(c={});var g=new I(this,a,b,c,!0);c.wa&&!c.pa&&chrome.cookies.getAll({url:c.wa},J(g,4));for(var f=0;f<a.length;f++)chrome.cookies.getAll({url:a[f][0]},J(g,f+5));if(g.c())return}e&&(c.pa=L(e));for(f=0;f<a.length;f++)a[f][4]=L(arguments[f+5]);var g=0,f=[a.length],h={8:4};h[54]=navigator.userAgent;h[7]=c.wa;h[110]=c.q;h[111]=c.pa;1<a.length&&(F(this,15,g,f,h),g=16,h={});for(var f=[0],k;k=a.shift();)h[6]=k[0],h[102]=k[2],h[50]=k[3],h[51]=k[4],
F(this,14,g,f,h)};function M(a,b,c,d){(b=b[c])?(b=d?b.replace(/\./g,"\\.").replace(/\?/g,".").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"):b.replace(/\?/g,".").replace(/\*/g,".*"),b="^(?:"+b+")$"):b="(?!)";a.c[c]=new RegExp(b,"i")}
function N(a,b,c,d,e,g,f,h){if(!d||a.c[-8]){var k=a.a[b];if(k){var m;m=new x;m=a.h[m.b]=m;var n=m.b;m.tabId=b;m.port=k;m.j=c;m.c=0;m.o=[];if(k=d&&!!e)m.w=!0,m.u=e,m.f=g,m.h=f,m.zoom=h,e.a||O(a,e);e="^(?:http|https|ftp|ftps|rtmp|rtmpt|rtmpe|mms)://";d&&(d=a.c[12])&&(d=d.replace(/\./g,"\\."),d=d.replace(/\*/g,".*"),d=d.replace(/\~/g,"(?:.*\\.)?"),e=e+"(?:[^\\/]*@)?(?:"+d,e+=")(?::\\d+)?(?:\\W|$)");m.e=P(a,b,[12,n,c,k,e]);m.v=0;m.e||E(a,n)}}}
function Q(a,b){if(b.Ha)return a.sendRequest(b,6),1;var c=b.F,d=b.statusCode;if(!c&&200!=d&&206!=d)return 1;var e=a.c,g=b.url,d=b.D,f=R(b.responseHeaders,"Content-Type"),h=R(b.responseHeaders,"Content-Disposition"),k=S(f).toLowerCase(),m="attachment"==S(h).toLowerCase();if(!c){var n=b.ga&&!m&&"text/html"==k;if(b.k)if(n){var r=a.o[[b.tabId,b.frameId]];r&&(r.k=!0);a.sendRequest(b,5)}else"application/json"==k&&(r=a.a[[b.tabId,b.frameId]])&&r.k&&(r.h=b.requestId,a.sendRequest(b,5));if(n)return 1}if(b.U||
!d&&!e[-9])return 1;var f=T(h,"filename")||T(f,"name"),u=!1,h=!1;f?u=h=!0:f=U(g);var n=na(f).toUpperCase(),r=c,v=!1;if(!c){if(!u){var p=ka[k];if(p)if(p=p.split("|"),n&&0<=p.indexOf(n))u=!0;else if(d||!n)n=p.shift(),u=!0;if(!n)if(d&&(p=R(b.responseHeaders,"Server"))&&p.toLowerCase().startsWith("gvs")&&f==ha)v=!0;else return 1;!n||u||!m&&k&&e[10].test(k)}if(d&&"ASF"==n){if((k=R(b.responseHeaders,"Content-Length"))&&102400>=parseInt(k))return 1;p=R(b.responseHeaders,"Server");if("DCLK-AdSvr"==p)return 1}d&&
e[3].test(n)?v=!0:e[1].test(n)&&(r=d?!(e[-4]||e[4].test(n)):!0)}if(!r&&!v)return 1;e=v?e[11]:c?null:e[9];g=new URL(g);if(e&&e.test(g.hostname))return 1;b.Ea=n;b.fileName=h?f:null;return a.sendRequest(b,r?2:4,c?2052:v?256:(d?4096:0)|(h||m?16:8))?r?3:2:0}
l.sendRequest=function(a,b,c){var d=a.requestHeaders,e=a.responseHeaders,g=a.oa,f=parseInt(a.requestId),h=a.port&&a.port.id,k=a.timeStamp,m=a.r;m&64&&(c|=2097152);"POST"==a.method&&(c|=512);var n=4>b?1:0;b=[f,h,Math.floor(k/1E3),Math.floor(k%1E3*1E3),m&31,b];f={};f[6]=oa(a.url);f[17]=a.p;f[4]=a.Ea;f[100]=a.fileName;f[8]=c;f[11]=V(d);f[13]=V(e);f[18]=V(g);a.J&&(f[14]=pa(a.J,R(d,"Content-Type")));a.S&&(f[19]=pa(a.S,R(g,"Content-Type")));if(a=this.a[a.tabId])f[7]=a.url,f[110]=a.title;return F(this,13,
n,b,f)};function W(a,b){delete a.d[b]}l.t=function(a,b,c){if(4294967295==a)this.f=null,c=!0;else{var d=this.e[a];if(d){c=d.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:d.a=3;window.setTimeout(this.t.bind(null,a,!1,!0),1E3);return}d.a=0;c=!0}}c&&F(this,8,32,[a])};
function X(a,b,c,d){var e=a.e[b],g=256;2==e.a&&(d?(g|=128,e.a=1):g|=64);var f,h,k,m,n;c&&(f=c.left,h=c.top,k=c.right||f+1,m=c.bottom||h+1,n=c.zoom,c=e.port.c)&&(f+=c.left,h+=c.top,k=Math.min(k+c.left,c.right),m=Math.min(m+c.top,c.bottom));F(a,9,g,[b,f,h,k,m,n])}
l.A=function(a){var b=this.b,c=[];if(a)(a=b[a])&&(a.n||a.s||c.push(a.i));else for(var d in b)a=b[d],a.n||a.s||c.push(a.i);if(c.length){b=[15,null,null];a={};var e=this.e;for(d in e){var g=e[d];g.a&&0<=c.indexOf(g.port.tabId)&&(g.b?(g=g.port,g.a||O(this,g,null,a),b[2]=d,g.postMessage(b)):X(this,d,null,!0))}}};function Y(a,b,c){if((b=a.b[b])&&!b.s){b=b.i;var d=c?0:2;c=c?32:64;var e=a.e,g;for(g in e){var f=e[g];f.a&&f.port.tabId==b&&f.a!=d&&(f.a=d,F(a,8,c,[g]))}}}
function Z(a,b,c,d){var e=a.I,g=(e&b)!=((c?63:32)&b);a.I=c?e|=b:e&=~b;g&&(c=a.c[-1],b=a.c[-2],c=a.sa=0!=c&&(e&c)==c,e=a.V=0!=b&&(e&b)==b,a.ta=(c||e)&&d||null)}l.Ua=function(a,b){var c=this.b[a];c&&(c.s=null,b&&(chrome.windows.get(a,null,this.B),chrome.tabs.query({windowId:a,active:!0},this.B)),this.A(a))};
l.B=function(a){a instanceof Array&&(a=a.shift());if(a&&(!a.url||!a.url.startsWith("chrome:"))){var b=a.windowId||a.id,c=this.b[b];if(c){if(a.windowId)c.i=a.id,a.width&&(c.$=a.width),a.height&&(c.Z=a.height);else{var d="fullscreen"==a.state,e=d!=c.n;c.width=a.width;c.height=a.height;c.left=a.left;c.top=a.top;c.Ga="maximized"==a.state;c.n="fullscreen"==a.state;e&&(d?Y(this,b):this.A(b))}a=c.scale;d=(c.width-c.$)/2;e=c.height-c.Z-d;c.border=Math.round(d*a);150>=e&&(c.aa=Math.round(e*a));(c=this.b[b])&&
c.G&&(a=c.border,d=c.scale,F(this,7,0,[b,a,c.aa,Math.round(c.width*d)-a,Math.round(c.height*d)-a]))}}};function O(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],g;g=a[b.b];b=g){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(g)}for(g=e.pop();b=e.pop();g=b)d=b.Da,c[2]=d,c[3]=b.frameId,c[4]=d?null:b.url,c[5]=d?null:b.p,g.postMessage(c)}function P(a,b,c){a=a.a;b=[b,null].toString();var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}
l.H=function(a){var b={file:"content.js",runAt:"document_start",allFrames:!0};620756992<this.ca&&(b.matchAboutBlank=!0);if(a instanceof Array)for(;a.length;)try{chrome.tabs.executeScript(a.shift().id,b)}catch(c){}else try{chrome.tabs.executeScript(a.id||a,b)}catch(d){}};function qa(a,b){var c=a.b[b];c&&null==c.G&&F(a,6,17,[b,0,c.width,c.height,c.left,c.top,c.scale])}l.Fa=function(a){for(;a.length;)this.ma(a.shift(),!0)};l.Ca=function(a){this.Y(a.linkUrl,a.pageUrl,4)};
l.ea=function(a,b){N(this,b.id,a.menuItemId==this.va)};l.La=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){var c=a.j||this.Ba++,d=b.id,e="top"==a.name;a.id=c;a.tabId=d;a.windowId=0>b.index?null:b.windowId;a.d=!0;a.e=!1;a.a=e;a.frameId=e?0:a.sender.frameId;a.f=0;a.url=a.sender.url||e&&b.url||null;a.p=null;a.sender=null;this.j[c]=a;e&&(this.a[d]=a);a.onMessage.addListener(this.Ma.bind(this,a));a.onDisconnect.addListener(this.Q);this.N(a)}};
l.Q=function(a,b){if(a.d){b||(a.d=!1);var c=this.e,d=this.d,e=this.h,g,f,h;for(h in c)if(g=c[h],g.port===a)g.a&&this.t(h),delete c[h];for(h in d)(f=d[h],f.port!==a||f.k)||delete d[h];for(h in e)e[h].port===a&&delete e[h];this.ta===a&&Z(this,63,!1);if(!b){c=a.tabId;d=a.frameId;e=[c,d].toString();g=this.o;for(h in g)e==g[h].a&&delete g[h];a.a&&delete this.a[c];delete this.a[[c,d]];delete this.j[a.id]}}};
l.Ma=function(a,b){switch(b[0]){case 21:var c=b[1];c&&(a.url=c,null==a.frameId&&this.N(a));break;case 22:var d=this.a,e=d[[a.tabId,b[2]]],c=b[4];e.Da=b[3];e.c=c;if(d=d[e.b])if(d=d.c)c.left+=d.left,c.top+=d.top,c.right=Math.min(c.right+d.left,d.right),c.bottom=Math.min(c.bottom+d.top,d.bottom);break;case 23:var c=a.windowId,g=a.tabId,f=b[1],d=b[2],e=b[4],h=this.b[c];if(f){if(f=E(this,f)){var h=g==h.i&&!h.n,k=!d||!e;k&&(d=g);if(g=b[7])f.a&&f.q&&f.a!=f.q||(f.a=g),f.q=g;var m=D(this,d,a,k?null:b[5],k?
null:b[6]),n=h&&!m.a;m.a=h?1:2;f instanceof z&&$(this,f,2,(h?128:64)|(k?512:0),c,d,g);k||(X(this,d,e),n&&window.setTimeout(this.A.bind(null,c),3E3))}}else b[3]?(this.t(d,!0),delete this.e[d]):e&&g==h.i&&!h.n&&X(this,d,e,!0);break;case 24:c=b[2];(d=this.h[b[1]])&&c&&(d.a&&d.q&&d.a!=d.q||(d.a=c),d.q=c);break;case 25:D(this,b[1],a,b[2],b[3]);break;case 26:N(this,a.tabId,!0,!0,a,b[1],b[2],b[3]);break;case 27:if(c=this.h[b[1]]){d=c.o;if(e=b[4])if("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array){if(f=
b[5])for(h=0;h<e.length;h++)e[h][3]=f;Array.prototype.push.apply(d,e)}b[3]&&(c.c+=b[3]);b[6]&&(c.pageUrl=b[6]);b[7]&&(c.q=b[7]);++c.v<c.e||(E(this,c.b),c.w?(d=this.b[c.port.windowId])&&d.i==c.tabId&&c.c&&(c.frame=c.u.c,e=c.zoom,F(this,10,0,[4294967295,d.id,Math.round(c.f*e)+d.border,Math.round(c.h*e)+d.aa,0,c.c]),this.f=c.tabId,P(this,c.tabId,[13,!0])):d.length?this.ra(d,c.j,c.I):window.alert(chrome.i18n.getMessage("cannot_find_links")))}break;case 28:this.t(4294967295);break;case 29:ra(this,a.windowId,
a.tabId);break;case 30:ra(this,a.windowId,a.tabId,b[1],b[2]);break;case 31:(c=ia[b[1]])&&Z(this,c,b[2],a);break;case 32:0==b[1]&&Z(this,32,b[2],a);break;case 33:Z(this,63,!1);break;case 34:if(c=b[3],d=a.h||a.requestId)d=[d,b[2]],e={},e[110]=b[1],e[115]=c,F(this,16,32,d,e)}};
l.Ka=function(a){var b=a.d,c=a.f,d=a.a,e;if(1==b){var g=d[0];if(e=this.v[g])b=e.d,delete this.v[g]}switch(b){case 3:this.P=-1;this.W=a[13]||"m"+d[2];if(c=d[4]){c=c/96;a=this.ca;this.T=620756992>a?1:620756992<a&&621284967>a?c:637534208<a&&638078312>a?c:1.25<c?c:1;c=this.b;a=this.T;for(var f in c)d=c[f],d=[f,d.G,d.width,d.height,d.left,d.top,d.scale=a],F(this,6,17,d)}this.X&&this.L();break;case 4:f=this.c;f[-9]=0<(c&64);f[-8]=0<(c&32);f[-4]=0<(c&2);f[-1]=d[0];f[-2]=d[1];f[12]=a[12];M(this,a,1);M(this,
a,2);M(this,a,3);M(this,a,4);M(this,a,10);M(this,a,9,!0);M(this,a,11,!0);if(f=a[13])this.W=f;if(!this.O){this.O=!0;this.l(chrome.runtime.onConnect,this.La);this.l(chrome.webNavigation.onCommitted,this.ha);this.l(chrome.webNavigation.onHistoryStateUpdated,this.Ja);this.l(chrome.webRequest.onBeforeRequest,this.ja,{urls:["http://*/*"],types:["main_frame","sub_frame"]},["blocking"]);this.l(chrome.webRequest.onBeforeRequest,this.ja,{urls:["https://*/*"],types:["main_frame","sub_frame"]},["blocking","requestBody"]);
this.l(chrome.webRequest.onBeforeSendHeaders,this.ka,{urls:["http://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["requestHeaders"]);this.l(chrome.webRequest.onBeforeSendHeaders,this.ka,{urls:["https://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["blocking","requestHeaders"]);this.l(chrome.webRequest.onHeadersReceived,this.la,{urls:["http://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["responseHeaders"]);
this.l(chrome.webRequest.onHeadersReceived,this.la,{urls:["https://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["blocking","responseHeaders"]);this.l(chrome.webRequest.onResponseStarted,this.Sa,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});this.l(chrome.webRequest.onErrorOccurred,this.Ra,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});for(f=0;f<this.u.length;f++)chrome.contextMenus.update(this.u[f],
{enabled:!0});chrome.tabs.query({url:t[0]},this.H);chrome.tabs.query({url:t[1]},this.H)}break;case 5:f=d[0];(a=this.b[f])?(c=0!=(c&128),a.n!=c&&(a.n=c)&&Y(this,f)):this.na(f);break;case 6:f=e.a[0];c=d[1];if(f=this.b[f])f.G=c;break;case 8:f=d[0];c=c&32;if(4294967295==f)P(this,this.f,[13,!1]),this.f=null;else if(f=this.e[f])f.a=c?0:2;break;case 11:f=d[0];4294967295==f&&(N(this,this.f,!0,!0),this.f=null);break;case 12:try{var h=a.a[5],k=a[4];f=4==h?2:3;if((1==h||2==h)&&G(this,a)){if(this.c[3].test(k))1==
h?f=4:h=4;else if(this.c[-4]||this.c[4].test(k))f=4;a[8]|=256}if(4==h){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.qa(a)}else $(this,a,f)}catch(m){$(this,a,0)}break;case 1:break;default:!e&&c&1&&F(this,1,0,[a.e,0,0,0])}};
l.qa=function(a,b,c){try{if(!a.g)if(!b){var d=new I(this,a,!0);this.fa(a,null,d)||chrome.windows.getLastFocused(null,J(d,2));if(d.c())return}else if(c){var e=this.b[c.id],g=this.a[e&&e.i];g&&(a.g=g.id)}g=this.j[a.g];if(!g)return $(this,a,0);var f;var h=a.b;h||(h=x.prototype.d++,a.b=h,this.h[h]=a);f=h;if(!g.a){var k=this.a[g.tabId];k&&k.postMessage([14,f])}var m=[15,f,null,a[6],a[17],a[50],a[31]];g.a||O(this,g,f);g.postMessage(m)}catch(n){$(this,a,0)}};
function $(a,b,c,d,e,g,f){-1!=c&&(e=[b.e,c,e,g],g={},g[8]=b[8],f&&(g[110]=f),F(a,1,d|(0==c?4:2),e,g))}l.ha=function(a,b){var c=this.a[[a.tabId,a.frameId]];if(c)if(b){var d=a.url;d!=c.url&&(c.url=d,c.f++,w.test(d)&&(c.k=!0),this.Q(c,!0),c.postMessage([17,!1,c.k]))}else this.Q(c)};l.Ja=function(a){return this.ha(a,!0)};
l.ma=function(a,b){var c=a.id;this.b[c]={id:c,width:a.width,height:a.height,left:a.left,top:a.top,scale:this.T,border:8,aa:73,Ga:"maximized"==a.state,n:"fullscreen"==a.state,Z:0,$:0,i:0,G:null,s:null};chrome.tabs.query({windowId:c,active:!0},this.B);chrome.tabs.query({windowId:c,url:t[0]},this.H);chrome.tabs.query({windowId:c,url:t[1]},this.H);b&&qa(this,c)};l.na=function(a){F(this,5,32,[a]);delete this.b[a]};l.Ta=function(a){qa(this,a)};
l.Qa=function(a,b,c){var d=c.windowId,e=this.b[d];e&&!e.i&&this.B(c);"complete"==b.status&&(a=this.a[a])&&!a.e&&(a.e=!0,this.A(d))};l.Oa=function(a){this.I=0;this.f&&this.t(4294967295);var b=a.windowId;a=a.tabId;var c=this.a[a];c&&!c.windowId&&(c.windowId=b);if(c=this.b[b])Y(this,b),c.i=a,chrome.tabs.get(a,this.B),this.A(b)};l.Pa=function(a,b){var c=b.Wa,d=this.j,e;for(e in d)(port=d[e])&&port.tabId==a&&(port.windowId=c);Y(this,c,!0)};
function ra(a,b,c,d,e){a.f&&a.t(4294967295);var g=a.b[b];g&&g.i==c&&(d&&(g.$=d),e&&(g.Z=e),Y(a,b),g.s&&window.clearTimeout(g.s),g.s=window.setTimeout(a.Ua.bind(null,b,d||e),250))}
l.ja=function(a){var b=a.tabId,c=a.frameId;if(!(0>b||0>c)){var d=a.requestId,e=a.url,g=K(e);if(ga.test(e))return a=this.a[b],this.Y("idmreg"+e.substr(e.indexOf(":")),a&&a.url),{redirectUrl:chrome.extension.getURL("captured.html")};var f=[b,c].toString(),h=this.o,b=f in h?h[f]:h[f]=new la(b,c,a.parentFrameId);b.b!=d&&(b.b=d,b.p=e,b.url=null,b.k=!1);if(!this.V&&g&128&&"POST"==a.method&&a.requestBody){e=a.requestBody;if(g=e.raw)for(b=0;b<g.length&&(g[b].bytes||(g=null));b++);if(g||e.formData)(g=this.d[d])?
g.requestBody=e:this.d[d]=a}}};
l.ka=function(a){var b=a.tabId;if(0<b){var c=a.requestId,d=a.url,e=a.method,g=K(d);if(!g||"GET"!=e&&"POST"!=e)return W(this,c);a.F=this.sa;a.U=this.V;var f=this.d[c];f&&(a.port=f.port,a.J=f.requestBody,f.r&&(a.p=f.p||f.url,a.oa=f.oa||f.requestHeaders,a.S=f.S||f.J,a.F=f.F,a.U=f.U));var f=a.F,h=a.type,k=a.ga=h.endsWith("_frame");if(!a.port&&!(a.port=this.a[[b,a.frameId]])&&!k||"POST"==e&&g&128&&!a.J||!f&&k&&!d.includes("?")&&(b=U(d),(b=na(b).toUpperCase())&&this.c[2].test(b)))return W(this,c);d.includes("#")&&
(a.url=oa(d));a.r=g;a.D=0<=ca.indexOf(h);a.k=w.test(d);this.d[c]=a;if(f&&g&128&&3==Q(this,a))return{cancel:!0}}};
l.la=function(a){var b=a.requestId,c=this.d[b];if(c){var d=a.responseHeaders;if("image"==c.type){var e=R(d,"Content-Type");if(e&&e.toLowerCase().startsWith("image/"))return W(this,b)}"quic"==R(d,"Client-Protocol")?c.r|=64:(b=R(d,"Alternate-Protocol"))&&b.endsWith(":quic,p=0")&&"chunked"!=R(d,"Transfer-Encoding")&&(c.r|=64);if(c.r&192&&(a=a.statusLine,b=parseInt(a.split(" ",2).pop()),c.statusLine=a,c.statusCode=b,c.Ha=0<=da.indexOf(b),c.responseHeaders=d,3==Q(this,c)))return{responseHeaders:[{name:"Connection",
value:"close"},{name:"Content-Type",value:"multipart/related"},{name:"Content-Length",value:"0"}]}}};l.Sa=function(a){a=a.requestId;var b=this.d[a];if(b){if(b.ga){var c=this.o[[b.tabId,b.frameId]];c&&(c.url=b.url)}b.D?this.d[a]={url:b.url,port:b.port}:W(this,a)}};l.Ra=function(a){W(this,a.requestId)};
l.L=function(a,b,c,d,e){if(void 0===e&&(this.X=!1,e=new I(this),chrome.app?a=chrome.app.getDetails():chrome.management.get(chrome.i18n.getMessage("@@extension_id"),J(e,0)),chrome.storage?chrome.storage.local.get("version",J(e,1)):window.localStorage&&(b=window.localStorage.getItem("version")||""),chrome.extension.isAllowedIncognitoAccess(J(e,2)),chrome.management.get(s,J(e,3)),e.c(a,b,c,d,!0)))return;"object"==typeof a&&(a=a.version||"");"object"==typeof d&&(d=d.enabled&&d.version||"");d&&chrome.management.setEnabled(s,
!1);"object"==typeof b&&(b=b.version||"");a&&a!=b&&null!=b&&(chrome.storage?chrome.storage.local.set({version:a}):window.localStorage.setItem("version",a),d=this.W,d&&b||(a="current="+a,b&&(a+="&previous="+b),c&&(a+="&incognito=1"),d&&(a+="&manager="+d),chrome.tabs.create({url:chrome.extension.getURL("welcome.html?"+a)})))};l.l=function(a){var b=Array.prototype.slice.call(arguments);this.ua.push(b);a.addListener.apply(a,b.slice(1))};
function I(a){this.caller=arguments.callee.caller;this.d=a;this.b=Array.prototype.slice.call(arguments,1);this.a=0}function J(a,b){a.a++;return a.f.bind(a,b)}I.prototype.c=function(){return this.a?(arguments.length&&(this.b=Array.prototype.slice.call(arguments)),!0):!1};I.prototype.f=function(a,b){this.b[a]=b;0==--this.a&&this.caller.apply(this.d,this.b)};
I.prototype.e=function(a,b,c){var d=Array.prototype.slice.call(arguments,3);c&&(d=c.concat(d));a.apply(b,d);this&&0==--this.a&&this.caller.apply(this.d,this.b)};function H(a){var b=Array.prototype.slice.call(arguments,1),c=b[b.length-1];c instanceof I?c.a++:c=null;return I.prototype.e.bind(c,arguments.callee.caller,a,b)}function oa(a){var b=a.lastIndexOf("#");return 0>b||b<a.indexOf("?")?a:a.substr(0,b)}function L(a){var b="",c;for(c in a)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}
function V(a){if(!a||!a.length)return null;for(var b="",c=0;c<a.length;c++)b+=a[c].name,b+=": ",b+=a[c].value,b+="\n";return b}function R(a,b){if(!a)return null;b=b.toLowerCase();for(var c in a)if(a[c].name.toLowerCase()==b)return a[c].value;return null}
function T(a,b){if(!a)return null;b=b.toLowerCase();var c=a.split(";");c.shift();for(var d in c){var e=c[d],g=e.indexOf("=");if(0<g){var f=e.substr(0,g).trim().toLowerCase(),h="*"==f[f.length-1];h&&(f=f.substr(0,f.length-1).trimRight());if(f==b)return c=e.substr(g+1).trim(),d=c.length-1,'"'==c[0]&&'"'==c[d]&&(c=c.substring(1,d)),h&&(c=c.split("'",3).pop()),unescape(c)}else if(0>g&&e.trim().toLowerCase()==b)return""}return null}function S(a){return a&&unescape(a.split(";",1).shift().trim())||""}
function pa(a,b){if(!a)return null;var c=a.raw;if(c){for(var d=String.fromCharCode,e="",g=0;g<c.length;g++){var f=c[g].bytes;if(!f)return null;for(var f=new Uint8Array(f),h=f.length,k=0;k<h;k++)e+=d(f[k])}return e}c=a.formData;if(!c)return null;g=S(b).toLowerCase();e=[];if("application/x-www-form-urlencoded"==g)for(d in c)for(f=c[d],d=d.split(" ").map(encodeURIComponent).join("+"),g=0;g<f.length;g++)e.length&&e.push("&"),e.push(d,"=",f[g].split(" ").map(encodeURIComponent).join("+"));else if("multipart/form-data"==
g){(h=T(b,"boundary"))||(h="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in c)for(f=c[d],g=0;g<f.length;g++)e.push("--",h,'\r\nContent-Disposition: form-data; name="',d,'"\r\n\r\n',f[g],"\r\n");e.push("--",h,"--\r\n")}else return null;return e.join("")}function na(a){return(a=fa.exec(a))?a[1]:""}function K(a,b){var c=a.split("://",1).shift().toLowerCase(),c=ja[c]||0;return b?c&31:c}function U(a){return(a=ea.exec(a))?a[1]:""}
String.prototype.startsWith||(String.prototype.startsWith=function(a){return 0==this.indexOf(a)});String.prototype.endsWith||(String.prototype.endsWith=function(a){var b=this.length-a.length;return 0<=b&&this.indexOf(a,b)==b});String.prototype.includes||(String.prototype.includes=function(a){return 0<=this.indexOf(a)});new C;
